server:
  port: 8091

# create and drop tables and sequences, loads import.sql
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: dSK1FSoxnUo=1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 3KB
      max-file-size: 100MB
      max-request-size: 110 MB

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug